stages:
  - build
  - release

variables:
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

image: registry.gitlab.com/ericvh/docker-buildx-qemu
services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
    
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - update-binfmts --enable
    - docker buildx create --driver docker-container --use
    - docker buildx build --no-cache --pull --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t $CONTAINER_DEV_IMAGE --build-arg CI_COMMIT_SHORT_SHA .

release:
  stage: release
  only:
  - master
  script:
    - docker buildx imagetools create -t $CONTAINER_RELEASE_IMAGE $CONTAINER_DEV_IMAGE 

